import bs4
import requests
import csv

def function1():

    base_url = "https://www.kalerkantho.com/online"
    catagory = "national"
    #next_page = "18"

    national_catagory = [""]

    all_url = []
    i=0
    for page_index in national_catagory:
        i=i+1
        if i==1:
            complete_url =  base_url + '/' + catagory + '/'#+ next_page + '/'
            #print(complete_url + '18')
            #print(complete_url + '36')
        else:
            complete_url = base_url + '/' + catagory + '/' +str(page_index)
            #print(complete_url + '18')
            #print(complete_url + '36')
        all_url.append([complete_url])
        all_url.append([complete_url+'18'])
        all_url.append([complete_url + '36'])
        all_url.append([complete_url + '54'])
        all_url.append([complete_url + '72'])
        all_url.append([complete_url + '90'])
        all_url.append([complete_url + '108'])
        all_url.append([complete_url + '126'])
        all_url.append([complete_url + '162'])
        all_url.append([complete_url + '180'])
        all_url.append([complete_url + '198'])
        all_url.append([complete_url + '216'])
        all_url.append([complete_url + '234'])
        all_url.append([complete_url + '252'])
        all_url.append([complete_url + '270'])
        all_url.append([complete_url + '288'])
        all_url.append([complete_url + '306'])
        all_url.append([complete_url + '324'])
        all_url.append([complete_url + '342'])
        all_url.append([complete_url + '360'])
        all_url.append([complete_url + '378'])
        all_url.append([complete_url + '396'])
        all_url.append([complete_url + '414'])
        all_url.append([complete_url + '432'])
        all_url.append([complete_url + '450'])
        all_url.append([complete_url + '468'])
        all_url.append([complete_url + '486'])
        all_url.append([complete_url + '504'])
        all_url.append([complete_url + '522'])
        all_url.append([complete_url + '540'])
        all_url.append([complete_url + '558'])
        all_url.append([complete_url + '576'])
        all_url.append([complete_url + '594'])
        all_url.append([complete_url + '612'])
        all_url.append([complete_url + '630'])
        all_url.append([complete_url + '648'])
        all_url.append([complete_url + '666'])
        all_url.append([complete_url + '684'])
        all_url.append([complete_url + '702'])
        all_url.append([complete_url + '720'])
        all_url.append([complete_url + '738'])
        all_url.append([complete_url + '756'])
        all_url.append([complete_url + '774'])
        all_url.append([complete_url + '792'])
        all_url.append([complete_url + '810'])
        all_url.append([complete_url + '828'])
        all_url.append([complete_url + '846'])
        all_url.append([complete_url + '864'])
        all_url.append([complete_url + '882'])
        all_url.append([complete_url + '900'])
        all_url.append([complete_url + '918'])
        all_url.append([complete_url + '936'])
        all_url.append([complete_url + '954'])
        all_url.append([complete_url + '972'])
        all_url.append([complete_url + '990'])
        all_url.append([complete_url + '1008'])
        all_url.append([complete_url + '1026'])
        all_url.append([complete_url + '1044'])
        all_url.append([complete_url + '1062'])
        all_url.append([complete_url + '1080'])
        all_url.append([complete_url + '1098'])
        all_url.append([complete_url + '1116'])
        all_url.append([complete_url + '1134'])
        all_url.append([complete_url + '1152'])
        all_url.append([complete_url + '1170'])
        all_url.append([complete_url + '1188'])
        all_url.append([complete_url + '1206'])
        all_url.append([complete_url + '1224'])
        all_url.append([complete_url + '1242'])
        all_url.append([complete_url + '1260'])
        all_url.append([complete_url + '1278'])
        all_url.append([complete_url + '1296'])
        all_url.append([complete_url + '1314'])
        all_url.append([complete_url + '1332'])
        all_url.append([complete_url + '1350'])
        all_url.append([complete_url + '1368'])
        all_url.append([complete_url + '1386'])
        all_url.append([complete_url + '1404'])
        all_url.append([complete_url + '1422'])
        all_url.append([complete_url + '1440'])
        all_url.append([complete_url + '1458'])
        all_url.append([complete_url + '1476'])
        all_url.append([complete_url + '1494'])
        all_url.append([complete_url + '1512'])
        all_url.append([complete_url + '1530'])
        all_url.append([complete_url + '1548'])
        all_url.append([complete_url + '1566'])
        all_url.append([complete_url + '1584'])
        all_url.append([complete_url + '1602'])
        all_url.append([complete_url + '1620'])
        all_url.append([complete_url + '1638'])
        all_url.append([complete_url + '1656'])
        all_url.append([complete_url + '1674'])
        all_url.append([complete_url + '1692'])
        all_url.append([complete_url + '1710'])
        all_url.append([complete_url + '1728'])
        all_url.append([complete_url + '1746'])
        all_url.append([complete_url + '1764'])
        all_url.append([complete_url + '1782'])
        all_url.append([complete_url + '1800'])
        all_url.append([complete_url + '1818'])
        all_url.append([complete_url + '1836'])
        all_url.append([complete_url + '1854'])
        all_url.append([complete_url + '1872'])
        all_url.append([complete_url + '1890'])
        all_url.append([complete_url + '1908'])
        all_url.append([complete_url + '1926'])
        all_url.append([complete_url + '1944'])
        all_url.append([complete_url + '1962'])
        all_url.append([complete_url + '1980'])
        all_url.append([complete_url + '1998'])
        all_url.append([complete_url + '2016'])
        all_url.append([complete_url + '2034'])
        all_url.append([complete_url + '2052'])
        all_url.append([complete_url + '2070'])
        all_url.append([complete_url + '2088'])
        all_url.append([complete_url + '2106'])
        all_url.append([complete_url + '2124'])
        all_url.append([complete_url + '2142'])
        all_url.append([complete_url + '2160'])
        all_url.append([complete_url + '2178'])
        all_url.append([complete_url + '2196'])
        all_url.append([complete_url + '2214'])
        all_url.append([complete_url + '2232'])
        all_url.append([complete_url + '2250'])
        all_url.append([complete_url + '2268'])
        all_url.append([complete_url + '2304'])
        all_url.append([complete_url + '2322'])







    with open('main_page_url.csv',mode = 'w', newline='') as main_url_list:
        main_url_writer = csv.writer(main_url_list,delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

        for url in all_url:
            print(url)
            main_url_writer.writerow(url)

    main_url_list.close()
    return all_url
function1()
